## may just have users specify the config parameters we need in the run_snakemake.sh 

## environment variables (will soon contain singularity names/paths)
## should NOT be editable by users
## may just edit this in the actual snakefile rather than here 
fastqc_env: "workflow/envs/fastqc_env.yml"
mutliqc_env: "workflow/envs/multiqc_env.yml"
cutadapt_env: "workflow/envs/cutadapt_env.yml"
bowtie_env: "workflow/envs/bowtie_env.yml"
bbmap_env: "workflow/envs/bbmap_env.yml"

## sample ids are in a column named "sampleid" (required)
##sample_id_file: "path/to/sampleid/csv"

## path to raw sequencing file input directory 
##raw_seq_in: "path/to/raw_seq/in_dir"

