---
title: "count_file_wrangling"
output: html_document
date: "2024-10-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(broom)
library(magrittr)
library(edgeR)
```

**File paths**
```{r}
transE_high_s47_fp <- '../crispr_screen_out/count_output/transE-High_S47_L005_counts.txt'
transE_low_s45_fp <- '../crispr_screen_out/count_output/transE-Low_S45_L005_counts.txt'
transE_medium_s46_fp <- '../crispr_screen_out/count_output/transE-Medium_S46_L005_counts.txt'
transE_pre_s48_fp <- '../crispr_screen_out/count_output/transE-Pre_S48_L005_counts.txt'
```

**Reading in count files**
```{r}
transE_high_s47_counts <- read_tsv(transE_high_s47_fp)
transE_low_s45_counts <- read_tsv(transE_low_s45_fp)
transE_medium_s46_counts <- read_tsv(transE_medium_s46_fp)
transE_pre_s48_counts <- read_tsv(transE_pre_s48_fp)
```

**Adding a sampleid column to each counts table**
need to figure out how to automate this step 
```{r}
transE_high_s47_counts <- transE_high_s47_counts %>% 
  mutate(sampleid = paste('transE_high_s47'))

transE_low_s45_counts <- transE_low_s45_counts %>% 
  mutate(sampleid = paste('transE_low_s45'))

transE_medium_s46_counts <- transE_medium_s46_counts %>% 
  mutate(sampleid = paste('transE_medium_s46'))

transE_pre_s48_counts <- transE_pre_s48_counts %>% 
  mutate(sampleid = paste('transE_pre_s48'))
```

**Combining all the count tables**
```{r}
comb_counts <- rbind(transE_pre_s48_counts,
                     transE_low_s45_counts,
                     transE_medium_s46_counts,
                     transE_high_s47_counts)

## selected the Plus_reads column, idk if that was right
## taking the tibble from long to wide format w the sampleids as the columns
comb_counts_wide <- comb_counts %>% 
                      select(`#ID`, Plus_reads, sampleid) %>% 
                      spread(sampleid, Plus_reads)

## converting the tibble to a dataframe so I can set the id column as the rownames 
comb_counts_wide_df <- as.data.frame(comb_counts_wide)

rownames(comb_counts_wide_df) <- comb_counts_wide_df$`#ID`

## getting rid of the id column since its now the rownames 
comb_counts_wide_df <- subset(comb_counts_wide_df,
                              select = -`#ID`)
```

**Normalizing the counts**
they're now in counts per million
```{r}
norm_combCounts_df <- edgeR::cpm(comb_counts_wide_df)

norm_combCounts_df <- as.data.frame(norm_combCounts_df)
```

**Saving my outputs**
```{r}
## combined counts table in long format
write_tsv(comb_counts,
          '../crispr_screen_out/count_output/allSample_counts_long.tsv')

## combined counts table in wide format
write_tsv(comb_counts_wide_df,
          '../crispr_screen_out/count_output/allSample_counts_wide.tsv')

## normalized combined counts table in wide format
write_tsv(norm_combCounts_df,
          '../crispr_screen_out/count_output/norm-cpm_allSample_counts.tsv')
```

