raw_seq_in: raw_crispr_data
metadata_file: metadata.csv
bowtie_mismatches: '0'
vector_seq_used: TTGTGGAAAGGACGAAACACCG
vector_seq_minOverlap: '10'
vector_seq_error: '0.2'
crispr_sgRNA_index: human_brunello
