raw_seq_in: raw_crispr_data
metadata_file: metadata.csv
bowtie_mismatches: '0'
vector_seq_used: TTGTGGAAAGGACGAAACACCG
vector_seq_minOverlap: '10'
vector_seq_error: '0.2'
crispr_sgRNA_index: reference_data/human_crispr_sgRNA_brunello/human_crispr_sg_brunello
fastqc_env: workflow/envs/fastqc_env.yml
mutliqc_env: workflow/envs/multiqc_env.yml
cutadapt_env: workflow/envs/cutadapt_env.yml
bowtie_env: workflow/envs/bowtie_env.yml
bbmap_env: workflow/envs/bbmap_env.yml
